# Generated by Django 3.2.9 on 2021-11-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='title',
            field=models.CharField(max_length=5000),
        ),
    ]
