# Generated by Django 3.2.9 on 2021-11-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_blogpage_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='blog_text',
            new_name='blogs',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='user_name',
        ),
    ]
