# Generated by Django 3.2.9 on 2021-11-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20211129_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='user',
        ),
        migrations.DeleteModel(
            name='name',
        ),
    ]
