# Generated by Django 3.2.9 on 2021-12-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_auto_20211204_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='profile_pic',
        ),
    ]
