# Generated by Django 3.2.9 on 2021-12-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_remove_login_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
