# Generated by Django 3.2.9 on 2021-12-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_login_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='user_name',
            new_name='user',
        ),
    ]
